//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Polizas = new HashSet<Polizas>();
        }
    
        public int clienteId { get; set; }
        public string clienteApellido { get; set; }
        public string clienteNombre { get; set; }
        public Nullable<int> clienteDni { get; set; }
        public Nullable<System.DateTime> clienteFechaNacimiento { get; set; }
        public string clienteDomicilio { get; set; }
        public string clienteTelefono { get; set; }
        public string clienteMail { get; set; }
        public Nullable<int> clienteEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polizas> Polizas { get; set; }
    }
}
