//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculos()
        {
            this.Polizas = new HashSet<Polizas>();
        }
    
        public int vehiculoId { get; set; }
        public string vehiculoDominio { get; set; }
        public Nullable<int> vehiculoAnio { get; set; }
        public string vehiculoNumeroChasis { get; set; }
        public string vehiculoNumeroMotor { get; set; }
        public Nullable<int> modeloId { get; set; }
        public Nullable<int> vehiculoEstado { get; set; }
    
        public virtual Modelos Modelos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polizas> Polizas { get; set; }
    }
}
